### ISSUE TITLE
ergocub_sn_000 - Added washers in the neck joint

### ISSUE THREAD

**Issue by GiacomoVassallo13** [icub-tech-iit/robot-snapshots#12]
**Applicant:** *Giacomo Vassallo, @GiacomoVassallo13 

**Snapshot name:** *ergocub_sn_000*

**Field of application:**
- [X] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Modify the CAD Snapshot of ergoCub S/N:000, added a washer on the top of the motor assembly held by 4 others on the screws. Mech. assembly: IC_014_G_181.

![drutff](https://user-images.githubusercontent.com/70649516/142027623-1c862a07-126f-484a-891d-8f3da63cd06e.jpeg)

See the comments : 

- https://github.com/icub-tech-iit/proto/issues/2001#issuecomment-1313344124

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 6287 | 1pz | NECK SPACER (int. diameter 26 mm) |  |
| 1874 | 4pz | Washer - flat regular type - M2.5 (2.7x6x0.5) - SS A2 140HV - DIN125 A, ISO7089, UNI 6592 |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
[insert here the definition of done for this task]

## Resume

- **CAD update of Snapshot ergoCub_SN_000, assembly IC_014_G_181** **(Expressive face neck yaw joint assembly)**

   - [New CAD part, Alias 6287 cod. Wingst 6287](https://github.com/icub-tech-iit/robot-snapshots/issues/12#issuecomment-1319862308) and assembly
   - Mounted N 4 M2_5 washers UNI 6592

## Commit 
- [added spacer for neck snapshot ergocub_sn_000](https://github.com/icub-tech-iit/robot-snapshots/commit/87790076d8c8034881e263d6dbabc3b4cc6c2d16)
- [Mounted ring and washers on assembly IC_014_G_181](https://github.com/icub-tech-iit/robot-snapshots/commit/3e2e842781c2d740d05b1fab59d4c7c912b0d91e)

**Comment by GiacomoVassallo13** [comment]
Hi @Fabrizio69. I wrote 5 in the confusion of corrections. There are 5 washers in total, one above the bearing (the bigger one) and the other four to compress it against it (the small ones), as shown in the figure. The countersunk screws remain free because they hold the sensor support, the other two do not have the washer as this would make them collide against the support.

cc: @Elio75

**Comment by Fabrizio69** [comment]
> These two screws are not installed? ![image](https://user-images.githubusercontent.com/8970230/202394872-3f1a0033-2c5c-4944-bdda-1574f3b8c276.png)
>

Hi @fiorisi these two screws are used for the sensor support (missing in the photo).

**Comment by Elio75** [comment]
- I created a 6287 part as a neck assembly ring (assembly IC_014_G_181 new rev A2 ), 

![image](https://user-images.githubusercontent.com/53298662/202686145-82f68c7f-eb5f-4434-98d2-59e328c1bf77.png)
![image](https://user-images.githubusercontent.com/53298662/202687550-b9431cb5-812a-4ea3-a5a3-4c34559b6f47.png)

-  You have to understand why this compenetration exists in CAD

![image](https://user-images.githubusercontent.com/53298662/202688438-f951243e-1ccf-412d-a538-be9f50548429.png)

From the CAD you can see the bearing and the two Kaydon bearings fit well in the seats.

![image](https://user-images.githubusercontent.com/53298662/202690262-0f77eb8d-7ac3-43ef-9c73-acd08bbb26c3.png)

but the Kaydon bearing still overhangs by 0.1 mm as you can see from the picture below

![image](https://user-images.githubusercontent.com/53298662/202691139-0cb1ce22-0068-484f-bf00-b45db814c96f.png)

Talking to @GiacomoVassallo13  he told me that this interpenetration doesn't appear, otherwise the AEA bearing might stick out

@maggia80 @Fabrizio69 @fiorisi  @GiacomoVassallo13

**Comment by fiorisi** [comment]
If the CAD is correct the spacer shouldn't be used. Is in contact with both the outer and inner ring.
![image](https://user-images.githubusercontent.com/8970230/202699603-52aaad8e-31be-4539-8a78-73ffedecf42f.png)

I think that we have to design a proper spacer and add it to the official CAD model, not only to the snapshot.

**Comment by Elio75** [comment]
`If the CAD is correct the spacer shouldn't be used. Is in contact with both the outer and inner rings.`

![image](https://user-images.githubusercontent.com/53298662/202718459-2a304e40-df67-47d0-90c0-a5dec42c9822.png)

@maggia80 @Fabrizio69 @fiorisi @GiacomoVassallo13

**Comment by Fabrizio69** [comment]
Hi @Elio75 it's better to use a spacer that touch only the outer ring to avoid sliding

cc: @fiorisi

**Comment by Elio75** [comment]
But the bearing rests on the inner ring inside its seat

![image](https://user-images.githubusercontent.com/53298662/202737321-80c50b1d-0f9d-4b54-92c1-b6074201bb15.png)

CC @Fabrizio69

**Comment by Elio75** [comment]
chiudo
